# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :build do
    souyuz(
      platform: "android",
      build_configuration: "Release",
      keystore_path: ENV['KEYSTORE_PATH'],
      keystore_alias: ENV['KEYSTORE_ALIAS'],
      keystore_password: ENV['KEYSTORE_PASSWORD']
    )
  end
  
  lane :playstore do
	upload_to_play_store
  end
end