#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AuthenticatorPro.Shared.Resource", IsApplication=false)]

namespace AuthenticatorPro.Shared
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public static int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int colorAccentDark = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int colorDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int colorDarker = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int colorDarkest = 2130771972;
			
			// aapt resource value: 0x7F010005
			public static int colorLight = 2130771973;
			
			// aapt resource value: 0x7F010006
			public static int colorLighter = 2130771974;
			
			// aapt resource value: 0x7F010007
			public static int colorLightest = 2130771975;
			
			// aapt resource value: 0x7F010008
			public static int ic_launcher_background = 2130771976;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public static int auth_1and1 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int auth_3cx = 2130837505;
			
			// aapt resource value: 0x7F020002
			public static int auth_adobe = 2130837506;
			
			// aapt resource value: 0x7F020003
			public static int auth_adobe_dark = 2130837507;
			
			// aapt resource value: 0x7F020004
			public static int auth_algolia = 2130837508;
			
			// aapt resource value: 0x7F020005
			public static int auth_amazon = 2130837509;
			
			// aapt resource value: 0x7F020006
			public static int auth_amazon_dark = 2130837510;
			
			// aapt resource value: 0x7F020007
			public static int auth_appveyor = 2130837511;
			
			// aapt resource value: 0x7F020008
			public static int auth_aws = 2130837512;
			
			// aapt resource value: 0x7F020009
			public static int auth_azure = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public static int auth_backblaze = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public static int auth_battlenet = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public static int auth_binance = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public static int auth_bitbucket = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public static int auth_bitcoin = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public static int auth_bitfinex = 2130837519;
			
			// aapt resource value: 0x7F020010
			public static int auth_bitwarden = 2130837520;
			
			// aapt resource value: 0x7F020011
			public static int auth_blockchain = 2130837521;
			
			// aapt resource value: 0x7F020012
			public static int auth_cexio = 2130837522;
			
			// aapt resource value: 0x7F020013
			public static int auth_coinbase = 2130837523;
			
			// aapt resource value: 0x7F020014
			public static int auth_default = 2130837524;
			
			// aapt resource value: 0x7F020015
			public static int auth_default_dark = 2130837525;
			
			// aapt resource value: 0x7F020016
			public static int auth_digitalocean = 2130837526;
			
			// aapt resource value: 0x7F020017
			public static int auth_discord = 2130837527;
			
			// aapt resource value: 0x7F020018
			public static int auth_discord_dark = 2130837528;
			
			// aapt resource value: 0x7F020019
			public static int auth_dropbox = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public static int auth_electronicarts = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public static int auth_electronicarts_dark = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public static int auth_epicgames = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public static int auth_evernote = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public static int auth_facebook = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public static int auth_figma = 2130837535;
			
			// aapt resource value: 0x7F020020
			public static int auth_firefox = 2130837536;
			
			// aapt resource value: 0x7F020021
			public static int auth_gandi = 2130837537;
			
			// aapt resource value: 0x7F020022
			public static int auth_github = 2130837538;
			
			// aapt resource value: 0x7F020023
			public static int auth_github_dark = 2130837539;
			
			// aapt resource value: 0x7F020024
			public static int auth_gitlab = 2130837540;
			
			// aapt resource value: 0x7F020025
			public static int auth_gmail = 2130837541;
			
			// aapt resource value: 0x7F020026
			public static int auth_godaddy = 2130837542;
			
			// aapt resource value: 0x7F020027
			public static int auth_google = 2130837543;
			
			// aapt resource value: 0x7F020028
			public static int auth_googlecloudplatform = 2130837544;
			
			// aapt resource value: 0x7F020029
			public static int auth_googledrive = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public static int auth_googleplay = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public static int auth_guildwars2 = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public static int auth_hangouts = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public static int auth_heroku = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public static int auth_heroku_dark = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public static int auth_humblebundle = 2130837551;
			
			// aapt resource value: 0x7F020030
			public static int auth_ifttt = 2130837552;
			
			// aapt resource value: 0x7F020031
			public static int auth_ifttt_dark = 2130837553;
			
			// aapt resource value: 0x7F020032
			public static int auth_instagram = 2130837554;
			
			// aapt resource value: 0x7F020033
			public static int auth_instagram_dark = 2130837555;
			
			// aapt resource value: 0x7F020034
			public static int auth_jetbrains = 2130837556;
			
			// aapt resource value: 0x7F020035
			public static int auth_jetbrains_dark = 2130837557;
			
			// aapt resource value: 0x7F020036
			public static int auth_jottacloud = 2130837558;
			
			// aapt resource value: 0x7F020037
			public static int auth_kickstarter = 2130837559;
			
			// aapt resource value: 0x7F020038
			public static int auth_kraken = 2130837560;
			
			// aapt resource value: 0x7F020039
			public static int auth_lastpass = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public static int auth_linkedin = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public static int auth_logmein = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public static int auth_logmein_dark = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public static int auth_mailchimp = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public static int auth_mega = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public static int auth_microsoft = 2130837567;
			
			// aapt resource value: 0x7F020040
			public static int auth_namecheap = 2130837568;
			
			// aapt resource value: 0x7F020041
			public static int auth_nextcloud = 2130837569;
			
			// aapt resource value: 0x7F020042
			public static int auth_nintendo = 2130837570;
			
			// aapt resource value: 0x7F020043
			public static int auth_npm = 2130837571;
			
			// aapt resource value: 0x7F020044
			public static int auth_office365 = 2130837572;
			
			// aapt resource value: 0x7F020045
			public static int auth_onedrive = 2130837573;
			
			// aapt resource value: 0x7F020046
			public static int auth_origin = 2130837574;
			
			// aapt resource value: 0x7F020047
			public static int auth_outlook = 2130837575;
			
			// aapt resource value: 0x7F020048
			public static int auth_ovh = 2130837576;
			
			// aapt resource value: 0x7F020049
			public static int auth_paypal = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public static int auth_pluralsight = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public static int auth_privateinternetaccess = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public static int auth_protonmail = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public static int auth_protonvpn = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public static int auth_protonvpn_dark = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public static int auth_reddit = 2130837583;
			
			// aapt resource value: 0x7F020050
			public static int auth_rockstargames = 2130837584;
			
			// aapt resource value: 0x7F020051
			public static int auth_rockstargames_dark = 2130837585;
			
			// aapt resource value: 0x7F020052
			public static int auth_samsung = 2130837586;
			
			// aapt resource value: 0x7F020053
			public static int auth_scaleway = 2130837587;
			
			// aapt resource value: 0x7F020054
			public static int auth_skype = 2130837588;
			
			// aapt resource value: 0x7F020055
			public static int auth_slack = 2130837589;
			
			// aapt resource value: 0x7F020056
			public static int auth_snapchat = 2130837590;
			
			// aapt resource value: 0x7F020057
			public static int auth_teamviewer = 2130837591;
			
			// aapt resource value: 0x7F020058
			public static int auth_trello = 2130837592;
			
			// aapt resource value: 0x7F020059
			public static int auth_tutanota = 2130837593;
			
			// aapt resource value: 0x7F02005A
			public static int auth_twitch = 2130837594;
			
			// aapt resource value: 0x7F02005B
			public static int auth_twitter = 2130837595;
			
			// aapt resource value: 0x7F02005C
			public static int auth_uber = 2130837596;
			
			// aapt resource value: 0x7F02005D
			public static int auth_uber_dark = 2130837597;
			
			// aapt resource value: 0x7F02005E
			public static int auth_ubisoft = 2130837598;
			
			// aapt resource value: 0x7F02005F
			public static int auth_ubisoft_dark = 2130837599;
			
			// aapt resource value: 0x7F020060
			public static int auth_uplay = 2130837600;
			
			// aapt resource value: 0x7F020061
			public static int auth_uptimerobot = 2130837601;
			
			// aapt resource value: 0x7F020062
			public static int auth_wargaming = 2130837602;
			
			// aapt resource value: 0x7F020063
			public static int auth_wordpress = 2130837603;
			
			// aapt resource value: 0x7F020064
			public static int auth_wordpress_dark = 2130837604;
			
			// aapt resource value: 0x7F020065
			public static int auth_xbox = 2130837605;
			
			// aapt resource value: 0x7F020066
			public static int auth_xbox_dark = 2130837606;
			
			// aapt resource value: 0x7F020067
			public static int auth_youtube = 2130837607;
			
			// aapt resource value: 0x7F020068
			public static int ic_launcher_background = 2130837608;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public static int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int ic_launcher_foreground = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int ic_launcher_round = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
	}
}
#pragma warning restore 1591
